### ISSUE TITLE
Remove pages that unavaiable

### ISSUE THREAD

**Issue by phanhoang1803** [notnews/top_news#5]
We have encountered a significant number of sites that are no longer available. As a result, the current list of URLs is outdated and needs to be updated to reflect the current state of available sites.

So, if can, please remove unavailable urls.

**Comment by dwillis** [comment]
@phanhoang1803 Can you give us some examples of what you mean by no longer available and what you consider to be a significant number? Thanks.

**Comment by phanhoang1803** [comment]
@dwillis As I see that almost old urls of abcnews.go.com are unavailable

**Comment by dwillis** [comment]
@phanhoang1803 I see what you mean; the goal for the project is not to produce a list of current URLs but to record them as they are published. If you use the JSON files I would expect that you'd need to check the status code of each one when trying to access it.
